version: '3'
services:

  lunchrota:
    build: .
    restart: unless-stopped
    tty: true
    ports:
      - "8002:80"
    environment:
      APP_KEY: base64:+7JBw8tEr0aalfJbXOzc6CDxbNKVAKYFEDzXWuVGEVU=
      DB_HOST: db
      REDIS_HOST: redis
  db:
    image: mysql:5.7.30
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_DATABASE: homestead
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
  redis:
    image: redis:6.0.4
